// <auto-generated />
using System;
using ClientAccountApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClientAccountApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505231314_AddClientContractToInvoice")]
    partial class AddClientContractToInvoice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("ClientAccountApp.BankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("BIC")
                        .HasColumnType("TEXT");

                    b.Property<string>("BankName")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientInfoId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrespondentAccount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientInfoId");

                    b.HasIndex("ClientInfoId1");

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("ClientAccountApp.ClientContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientInfoId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContractNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentRelativePath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrganizationProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrganizationProfileId1")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientInfoId");

                    b.HasIndex("ClientInfoId1");

                    b.HasIndex("OrganizationProfileId");

                    b.HasIndex("OrganizationProfileId1");

                    b.ToTable("ClientContracts");
                });

            modelBuilder.Entity("ClientAccountApp.ClientFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientInfoId1")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientInfoId");

                    b.HasIndex("ClientInfoId1");

                    b.ToTable("ClientFiles");
                });

            modelBuilder.Entity("ClientAccountApp.ClientInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ContractGeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ContractSignedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectorFullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Inn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ogrn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("ClientAccountApp.ClientNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientInfoId1")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReminderDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientInfoId");

                    b.HasIndex("ClientInfoId1");

                    b.ToTable("ClientNotes");
                });

            modelBuilder.Entity("ClientAccountApp.ClientRecurringService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BillingCycle")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientInfoId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("GenerateDay")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdvanceBilling")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastGeneratedPeriodKey")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ServiceCatalogId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ServiceCatalogId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServiceName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VatRate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientInfoId");

                    b.HasIndex("ClientInfoId1");

                    b.HasIndex("ServiceCatalogId");

                    b.HasIndex("ServiceCatalogId1");

                    b.ToTable("ClientRecurringServices");
                });

            modelBuilder.Entity("ClientAccountApp.DigitalSignature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CertificationAuthority")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientInfoId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IssuedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientInfoId");

                    b.HasIndex("ClientInfoId1");

                    b.ToTable("DigitalSignatures");
                });

            modelBuilder.Entity("ClientAccountApp.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientContractId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentRelativePath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrganizationProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrganizationProfileId1")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PeriodFrom")
                        .HasColumnType("TEXT");

                    b.Property<string>("PeriodText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PeriodTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalWithVat")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalWithoutVat")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VatAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientContractId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClientInfoId");

                    b.HasIndex("OrganizationProfileId");

                    b.HasIndex("OrganizationProfileId1");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("ClientAccountApp.InvoiceDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientInfoId1")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentFormat")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InvoiceId1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrganizationProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrganizationProfileId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientInfoId");

                    b.HasIndex("ClientInfoId1");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("InvoiceId1");

                    b.HasIndex("OrganizationProfileId");

                    b.HasIndex("OrganizationProfileId1");

                    b.ToTable("InvoiceDocuments");
                });

            modelBuilder.Entity("ClientAccountApp.InvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountWithVat")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AmountWithoutVat")
                        .HasColumnType("TEXT");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InvoiceId1")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ServiceCatalogId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ServiceCatalogId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServiceName")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VatAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VatRate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("InvoiceId1");

                    b.HasIndex("ServiceCatalogId");

                    b.HasIndex("ServiceCatalogId1");

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("ClientAccountApp.OrganizationProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BankBic")
                        .HasColumnType("TEXT");

                    b.Property<string>("BankName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrespondentAccount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectorPosition")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Inn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kpp")
                        .HasColumnType("TEXT");

                    b.Property<string>("LegalAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoRelativePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ogrn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("SettlementAccount")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OrganizationProfiles");
                });

            modelBuilder.Entity("ClientAccountApp.ServiceCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultVatRate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ServicesCatalog");
                });

            modelBuilder.Entity("ClientAccountApp.BankAccount", b =>
                {
                    b.HasOne("ClientAccountApp.ClientInfo", "ClientInfo")
                        .WithMany()
                        .HasForeignKey("ClientInfoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ClientAccountApp.ClientInfo", null)
                        .WithMany("BankAccounts")
                        .HasForeignKey("ClientInfoId1");

                    b.Navigation("ClientInfo");
                });

            modelBuilder.Entity("ClientAccountApp.ClientContract", b =>
                {
                    b.HasOne("ClientAccountApp.ClientInfo", null)
                        .WithMany()
                        .HasForeignKey("ClientInfoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ClientAccountApp.ClientInfo", "ClientInfo")
                        .WithMany()
                        .HasForeignKey("ClientInfoId1");

                    b.HasOne("ClientAccountApp.OrganizationProfile", null)
                        .WithMany()
                        .HasForeignKey("OrganizationProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ClientAccountApp.OrganizationProfile", "OrganizationProfile")
                        .WithMany()
                        .HasForeignKey("OrganizationProfileId1");

                    b.Navigation("ClientInfo");

                    b.Navigation("OrganizationProfile");
                });

            modelBuilder.Entity("ClientAccountApp.ClientFile", b =>
                {
                    b.HasOne("ClientAccountApp.ClientInfo", null)
                        .WithMany()
                        .HasForeignKey("ClientInfoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ClientAccountApp.ClientInfo", "ClientInfo")
                        .WithMany("ClientFiles")
                        .HasForeignKey("ClientInfoId1");

                    b.Navigation("ClientInfo");
                });

            modelBuilder.Entity("ClientAccountApp.ClientNote", b =>
                {
                    b.HasOne("ClientAccountApp.ClientInfo", null)
                        .WithMany()
                        .HasForeignKey("ClientInfoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ClientAccountApp.ClientInfo", "ClientInfo")
                        .WithMany("Notes")
                        .HasForeignKey("ClientInfoId1");

                    b.Navigation("ClientInfo");
                });

            modelBuilder.Entity("ClientAccountApp.ClientRecurringService", b =>
                {
                    b.HasOne("ClientAccountApp.ClientInfo", null)
                        .WithMany()
                        .HasForeignKey("ClientInfoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ClientAccountApp.ClientInfo", "ClientInfo")
                        .WithMany()
                        .HasForeignKey("ClientInfoId1");

                    b.HasOne("ClientAccountApp.ServiceCatalog", null)
                        .WithMany()
                        .HasForeignKey("ServiceCatalogId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ClientAccountApp.ServiceCatalog", "ServiceCatalog")
                        .WithMany()
                        .HasForeignKey("ServiceCatalogId1");

                    b.Navigation("ClientInfo");

                    b.Navigation("ServiceCatalog");
                });

            modelBuilder.Entity("ClientAccountApp.DigitalSignature", b =>
                {
                    b.HasOne("ClientAccountApp.ClientInfo", "ClientInfo")
                        .WithMany()
                        .HasForeignKey("ClientInfoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ClientAccountApp.ClientInfo", null)
                        .WithMany("DigitalSignatures")
                        .HasForeignKey("ClientInfoId1");

                    b.Navigation("ClientInfo");
                });

            modelBuilder.Entity("ClientAccountApp.Invoice", b =>
                {
                    b.HasOne("ClientAccountApp.ClientContract", "ClientContract")
                        .WithMany("Invoices")
                        .HasForeignKey("ClientContractId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ClientAccountApp.ClientInfo", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("ClientAccountApp.ClientInfo", null)
                        .WithMany()
                        .HasForeignKey("ClientInfoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ClientAccountApp.OrganizationProfile", null)
                        .WithMany()
                        .HasForeignKey("OrganizationProfileId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ClientAccountApp.OrganizationProfile", "OrganizationProfile")
                        .WithMany()
                        .HasForeignKey("OrganizationProfileId1");

                    b.Navigation("Client");

                    b.Navigation("ClientContract");

                    b.Navigation("OrganizationProfile");
                });

            modelBuilder.Entity("ClientAccountApp.InvoiceDocument", b =>
                {
                    b.HasOne("ClientAccountApp.ClientInfo", null)
                        .WithMany()
                        .HasForeignKey("ClientInfoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ClientAccountApp.ClientInfo", "ClientInfo")
                        .WithMany()
                        .HasForeignKey("ClientInfoId1");

                    b.HasOne("ClientAccountApp.Invoice", null)
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ClientAccountApp.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId1");

                    b.HasOne("ClientAccountApp.OrganizationProfile", null)
                        .WithMany()
                        .HasForeignKey("OrganizationProfileId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ClientAccountApp.OrganizationProfile", "OrganizationProfile")
                        .WithMany()
                        .HasForeignKey("OrganizationProfileId1");

                    b.Navigation("ClientInfo");

                    b.Navigation("Invoice");

                    b.Navigation("OrganizationProfile");
                });

            modelBuilder.Entity("ClientAccountApp.InvoiceItem", b =>
                {
                    b.HasOne("ClientAccountApp.Invoice", null)
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ClientAccountApp.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId1");

                    b.HasOne("ClientAccountApp.ServiceCatalog", null)
                        .WithMany()
                        .HasForeignKey("ServiceCatalogId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ClientAccountApp.ServiceCatalog", "ServiceCatalog")
                        .WithMany()
                        .HasForeignKey("ServiceCatalogId1");

                    b.Navigation("Invoice");

                    b.Navigation("ServiceCatalog");
                });

            modelBuilder.Entity("ClientAccountApp.ClientContract", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("ClientAccountApp.ClientInfo", b =>
                {
                    b.Navigation("BankAccounts");

                    b.Navigation("ClientFiles");

                    b.Navigation("DigitalSignatures");

                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
